require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/reservations", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Api::V1::Reservation. As you add validations to Api::V1::Reservation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    payload
  }

  let(:invalid_attributes) {
    invalid_payload
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # Api::V1::ReservationsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "POST /create" do
    shared_examples "with valid parameters" do
      it "creates a new Reservation" do
        expect {
          post api_v1_reservations_url,
               params: valid_attributes, headers: valid_headers, as: :json
        }.to change { [ Guest.count, Reservation.count ] }.from([ 0, 0 ]).to([ 1, 1 ])
      end

      it "renders a JSON response reservation ID" do
        post api_v1_reservations_url,
             params: valid_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    describe "booking payload" do
      let(:payload) { JSON.parse(File.read(Rails.root.join('spec/fixtures/booking.json'))) }
      include_examples "with valid parameters"
    end

    describe "airbnb payload" do
      let(:payload) { JSON.parse(File.read(Rails.root.join('spec/fixtures/airbnb.json'))) }
      include_examples "with valid parameters"
    end

    context "with invalid parameters" do
      let(:invalid_payload) do
        JSON.parse(File.read(Rails.root.join('spec/fixtures/noemail.json')))
      end
      it "does not create Reservation" do
        expect {
          post api_v1_reservations_url,
               params: invalid_attributes, as: :json
        }.to change(Reservation, :count).by(0)
      end

      it "renders validation errors" do
        post api_v1_reservations_url,
             params: invalid_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.parsed_body).to include("errors" => [ "Email can't be blank" ])
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with different payload" do
      let(:invalid_payload) do
        { "foo" => "bar" }
      end

      it "renders unrecognized error" do
        post api_v1_reservations_url,
             params: invalid_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.parsed_body).to include("errors" => [ "Unrecognized payload" ])
      end
    end
  end
end
